---
title: "Sensitivity Analysis"
format: html
execute: 
  freeze: true
---

_Updated September 24, 2025_

```{r}
#| echo: false
#| warning: false
#| message: false

library(tidyverse)

```

## Weather values

### Finding a central value

```{r}
#| echo: false
#| warning: false
#| message: false

weathermns <- read.csv("data/weathergrid.csv")

midgrid <- weathermns$gridid[which(weathermns$distCenter==min(weathermns$distCenter))]

ggplot(weathermns, aes(Tmn, RAINmn, color = distCenter)) + geom_point() +
  scale_color_continuous(type = "viridis", direction=-1) +
  geom_point(data=weathermns |> dplyr::summarize(Tmn=mean(Tmn), RAINmn = mean(RAINmn)), color="red")

```

### Bumping up and down the most central grid data

```{r bump}
#| echo: false
#| warning: false
#| message: false

bumpsmns.df <- read.csv("data/weathergridmns.csv")

ggplot(weathermns, aes(Tmn, RAINmn, color = distCenter)) + geom_point() +
  scale_color_continuous(type = "viridis", direction=-1) +
  geom_point(data=weathermns |> dplyr::summarize(Tmn=mean(Tmn), RAINmn = mean(RAINmn)), color="red") +
  geom_point(data=bumpsmns.df, color="black", pch=1)

```

Lower rain values of the grid are compressed because days resulting in negative amounts of rain were replaced with 0.

## Results

```{r models_results}
#| echo: false
#| warning: false
#| message: false

corn.harvest <- readRDS("results/sensitivity_corn.rds") %>%
  left_join(bumpsmns.df %>% mutate(deltaT = as.character(deltT),
                                   deltaRAIN = as.character(deltR)))

soy.harvest <- readRDS("results/sensitivity_soy.rds") %>%
  left_join(bumpsmns.df %>% mutate(deltaT = as.character(deltT),
                                   deltaRAIN = as.character(deltR)))

```

### Corn harvest results

```{r corn_harvest}
#| echo: false
#| warning: false
#| message: false
#| fig-height: 10
#| fig-width: 8

ggplot(corn.harvest %>% filter(MODEL == "WL"), aes(Tmn, bshl_acr)) +
  geom_line(aes(color = deltaRAIN)) + scale_color_brewer(type="div",palette = "Spectral") + 
  geom_line(data=corn.harvest %>% filter(MODEL == "PP",deltaRAIN=="0"),color="grey",lty=2) + 
  facet_wrap(~soil, ncol=3) + egg::theme_article()

```

### Soy harvest results

```{r soy_harvest}
#| echo: false
#| warning: false
#| message: false
#| fig-height: 10
#| fig-width: 8

ggplot(soy.harvest %>% filter(MODEL == "WL"), aes(Tmn, bshl_acr)) +
  geom_line(aes(color = deltaRAIN)) + scale_color_brewer(type="div",palette = "Spectral") + 
  geom_line(data=soy.harvest %>% filter(MODEL == "PP",deltaRAIN=="0"),color="grey",lty=2) + 
  facet_wrap(~soil, ncol=3) + egg::theme_article()

```
